### ISSUE TITLE
Clicking doesn't work

### ISSUE THREAD

**Issue by triplrrr** [itsjohncs/particles-js#15] opened 2021-09-06 04:47 UTC
Clicking on a touchpad in latest firefox as of writing doesn't invert mouse's gravity.

**Comment by itsjohncs** [comment] 2021-10-08 01:20
Ah sorry, I didn't see this until now. Must've accidentally marked a notification as read when I shouldn't have.

Are you still experiencing this? I can't reproduce it on my computer and haven't had anyone else mention problems. I'm going to preemptively close this issue only because I won't remember to later if I don't hear back from you, but please let me know if you're still getting this. I'd love to figure out what's going on.

**Closed as completed by itsjohncs** 2021-10-08 01:20 UTC
